Captain-Thunk-Grace-Shopper/Grace-Shopper

server/api/index.js
server/api/products.js
server/db/models/index.js
server/db/models/product.js

Closes Issue #13

---

script/seed.js

seed file for products

---

client/store/index.js
client/store/products.js

feat(client): get products reducer

---

server/db/models/user.js

feat(user_model)- update user

---

client/components/navbar.js
client/store/products.js
package-lock.json

Closes #19

---

client/store/index.js
client/store/orders.js
server/api/index.js
server/api/order-items.js
server/api/orders.js
server/api/users.js
server/db/models/index.js
server/db/models/order-item.js
server/db/models/order.js

created schemas for both orders and order-items, and created sequeliz…e associations that link users to orders and orders to items

Resolves Issue #26

---

client/components/Products.spec.js
server/api/product.spec.js

products get route and component tests

product routes and component test

---

public/index.html

Closes #18

---

client/components/Products.js
client/components/SingleProduct.js
client/components/cart.js
client/components/cartItem.js
server/index.js

(feat: cart component rough draft)

---

script/seed.js
server/db/models/order-item.js
server/db/models/product.js

Closes #39

---

client/components/Home.js
client/components/cart.js
client/components/cartItem.js
server/api/orders.js

(feat) cart component revised

---

client/components/cart.js
client/store/orders.js
server/api/orders.js

feat(cart) updated

---

client/components/cart.js
client/components/cartItem.js
client/store/orders.js
server/api/orders.js
server/db/models/index.js

feat(cart) revised again

---

client/components/navbar.js
public/style.css

beginning navbar css

---

server/api/orders.js

deleted extra order route

---

client/components/checkout.js

Closes #42

---

client/app.js
client/components/Home.js
client/components/Products.js
public/style.css

All Groceries View utilizing flexbox, albeit messy 

---

server/api/orders.js
server/db/models/user.js

merged order/user with order/orderProducts

feat orders Route

---

server/api/order-items.js
server/api/orders.js
server/db/models/order.js

CLoses #54

---

client/components/Home.js
client/components/Products.js
client/components/cart.js
client/components/cartItem.js
client/store/orders.js
server/api/order-items.js
server/api/orders.js
server/db/models/order.js

feat: add to cart

---

client/components/Home.js
server/api/order-items.js

quick fix for loading all Products

---

client/components/Products.spec.js
server/api/product.spec.js
server/db/models/order.spec.js

commented out tests

---

.travis.yml

updated travis

---

client/components/cartItem.js
client/store/orders.js
server/api/order-items.js

users and guests can delete items from their cart

---

client/components/Products.spec.js
client/components/cart.js
client/components/checkout.js
public/style.css

a bit updated

---

client/components/cart.js
client/components/cartItem.js
client/store/orders.js
server/api/order-items.js

framework for put request to update cart

---

client/components/cart.js
client/components/cartItem.js
server/api/order-items.js
server/api/users.js

both guest and user carts update quantities in front and backend

---

client/components/SingleProduct.js

singleproductAddToCart

---

client/components/PastOrder.js
client/components/cart.js
client/components/navbar.js
client/components/user-home.js
client/components/user-home.spec.js
client/routes.js
client/store/index.js
client/store/past-orders.js
public/index.html
server/api/orders.js
server/db/models/order.js

working logic for past orders created store and reducer and as react components

Past orders

---

client/store/orders.js
server/api/order-items.js

refactored order reducer for addToCart

---

client/components/checkout.js
client/components/payment.js
client/store/orders.js
server/api/orders.js
server/api/users.js

checkout address taken care of

---

client/components/checkout.js
client/components/payment.js
client/store/orders.js
server/api/orders.js

checkout part done

---

script/seed.js

more item and description added

---

client/store/orders.js
server/api/orders.js

rendering closed cart

---

client/components/PastOrder.js
client/components/Products.js
client/components/auth-form.js
client/components/cart.js
client/components/cartItem.js
client/components/checkout.js
public/style.css
server/api/orders.js

added address and name fields to the PUT request when closing out the order so the database updates with all the information

Added address to order

---

client/components/PastOrder.js
client/components/Products.js
client/components/auth-form.js
client/components/cart.js
client/components/cartItem.js
client/components/checkout.js
public/style.css

css on main page, cart, login pages mostly complete
